sudo: required
services:
  - docker

before_install:
  - docker build -t mady/multi-docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true mady/multi-docker-react-test npm run test

after_success:
  - docker build -t mady/multi-docker-client ./client
  - docker build -t mady/multi-docker-nginx ./nginx
  - docker build -t mady/multi-docker-server ./server
  - docker build -t mady/multi-docker-worker ./worker
  # Log in to the docker CLI
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ### Take Those images and push to DockerHub
  - docker push mady/multi-docker-client
  - docker push mady/multi-docker-nginx
  - docker push mady/multi-docker-server
  - docker push mady/multi-docker-worker
  