sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mady/multi-docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mady/multi-docker-react-test npm run test
after_success:
  - docker build -t madykc/multi-docker-client ./client
  - docker build -t madykc/multi-docker-nginx ./nginx
  - docker build -t madykc/multi-docker-server ./server
  - docker build -t madykc/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ### Take Those images and push to DockerHub
  - docker push madykc/multi-docker-client
  - docker push madykc/multi-docker-nginx
  - docker push madykc/multi-docker-server
  - docker push madykc/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker-react"
  env: "MultiDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-256445997637"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
